export const homepageMarqueeTexts = [
  "all i want to feel is complete",
  "🧦",
  "i dont always have something to say",
  "welcome to my website",
  "public static void main args(String[] args)",
  "who am i // who are we",
  "bed",
  "please no running inside!",
  "i discover myself everytime i fall short",
  "she put me back together when im out of order",
  "mind over matter",
  "perfect",
  "¿? ¡!",
  "There is something beautiful coming, even if it is only the sun",
  "i might make it wonderful for once",
]
